Algoritmo "7-tabuada"
// 
//  
// Descrição   : Tabuada! (função)
// Autor(a)    : Weverton Alexandre Almeida
// Data atual  : 4/29/2022
Var
// Seção de Declarações das variáveis
    n, i: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Deseja a tabuada para qual valor? ")
   leia(n)

   para i de 0 ate 10 faca
      escreval(n, " x ", i, " = ", n * i)
   fimpara


Fimalgoritmo
