Algoritmo "8-Tabuada-enquanto"
// 
//  
// Descrição   : Tabuada usando enquanto! (função)
// Autor(a)    : Weverton Alexandre Almeida
// Data atual  : 4/29/2022
Var
// Seção de Declarações das variáveis 
   i, n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um número para a tabuada: ")
   leia(n)
   
   enquanto i <= 10 faca
   escreval(n, " x ", i, " = ", n*i)
    i <- i+1
   fimenquanto

Fimalgoritmo